env:
  global:
    secure: "MJYk5b0aeh+yOIgaZdgmqMD8o6ok5DX1vijpWAHAdxaD2u4U3Ij8HEKIZB5JSt2touH7dNNRd+5ToOg9mhPg8gow3XQgHQjHdlpvx0Ulwc6zL7N3+qyrzT1+nI/y+urv1T7zwelI5Yj4WhZrFZZ7lHNJipcaqhqEE5v2BSzV3Hc="

install: true

before_install:
  - sudo apt-get update
  - sudo apt-get install gnome-themes-standard
  - sudo apt-get install metacity
  - sudo apt-get install libwebkit-dev
 
language: java

jdk:
  - openjdk6

branches:
  only:
    - master

script: 
  - mvn -q clean verify -Dtarget-platform-classifier=eclipse-3.8
  - mvn -q clean verify -Dtarget-platform-classifier=eclipse-4.4

before_script:
  - "export DISPLAY=:99.0"
  - sh -e /etc/init.d/xvfb start
  - sleep 5
  - metacity --sm-disable --replace &
  - sleep 5
 
after_success: 
  - chmod a+x .travis-deploy.sh
  - ./.travis-deploy.sh

after_failure:
  - com.codeaffine.extras.jdt.test/target/surefire-reports/*.txt
  - cat com.codeaffine.extras.platform.test/target/surefire-reports/*.txt
